export const Users = [
  {
    id: 1,
    profilePicture: "person/1.jpeg",
    username: "Maria Popescu",
  },
  {
    id: 2,
    profilePicture: "person/2.jpeg",
    username: "Alexandru Ionescu",
  },
  {
    id: 3,
    profilePicture: "person/3.jpeg",
    username: "Ana Vasile",
  },
  {
    id: 4,
    profilePicture: "person/4.jpeg",
    username: "Mihai Radu",
  },
  {
    id: 5,
    profilePicture: "person/5.jpeg",
    username: "Ioana Stoian",
  },
  {
    id: 6,
    profilePicture: "person/6.jpeg",
    username: "Vlad Munteanu",
  },
  {
    id: 7,
    profilePicture: "person/7.jpeg",
    username: "Cristina Dumitru",
  },
  {
    id: 8,
    profilePicture: "person/8.jpeg",
    username: "Andrei Constantinescu",
  },
  {
    id: 9,
    profilePicture: "person/9.jpeg",
    username: "Laura Marin",
  },
  {
    id: 10,
    profilePicture: "person/10.jpeg",
    username: "Bogdan Florea",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "O zi minunată! Vremea este superbă!",
    photo: "post/1.jpeg",
    date: "5 minute în urmă",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    desc: "Am ieșit la o plimbare cu motorul! #aventura",
    photo: "post/2.jpeg",
    date: "15 minute în urmă",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Când viața îți dă lămâi, fă limonadă!",
    photo: "post/3.jpeg",
    date: "1 oră în urmă",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    desc: "O după-amiază de relaxare acasă.",
    photo: "post/4.jpeg",
    date: "4 ore în urmă",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    desc: "O plimbare cu mașina pe plajă! #ocean",
    photo: "post/5.jpeg",
    date: "5 ore în urmă",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "post/6.jpeg",
    date: "1 zi în urmă",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Am testat noul meu obiectiv. Iubesc fotografia!",
    photo: "post/7.jpeg",
    date: "2 zile în urmă",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    desc: "O seară de neuitat alături de prieteni.",
    photo: "post/8.jpeg",
    date: "3 zile în urmă",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Am găsit un loc magic! 🏞️",
    photo: "post/9.jpeg",
    date: "5 zile în urmă",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: "post/10.jpeg",
    date: "1 săptămână în urmă",
    userId: 10,
    like: 104,
    comment: 12,
  },
];